name: cd

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v16

    - name: Build flake docs
      run: nix develop --command dune build @doc --display=short

    - name: Deploy docs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: gh-pages
        folder: _build/default/_doc/_html/
